/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Quote = IDL.Record({ 'text' : IDL.Text, 'author' : IDL.Text });

export const idlService = IDL.Service({
  'addQuote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAuthorQuotes' : IDL.Func([IDL.Text], [IDL.Vec(Quote)], ['query']),
  'getQuotesSortedByAuthor' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Quote = IDL.Record({ 'text' : IDL.Text, 'author' : IDL.Text });
  
  return IDL.Service({
    'addQuote' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAuthorQuotes' : IDL.Func([IDL.Text], [IDL.Vec(Quote)], ['query']),
    'getQuotesSortedByAuthor' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };